update docker-composer to use rafay9/judge0:latest

diff --git a/scripts/server b/scripts/server
--- a/scripts/server
+++ b/scripts/server
@@ -3,6 +3,7 @@
 #
 # Usage: ./scripts/server
 #
+echo "scripts/server:Starting server..."
 source ./scripts/load-config
 export | sudo tee /api/environment
 
@@ -10,7 +11,14 @@ for i in $(seq 1 $RESTART_MAX_TRIES); do
     [[ -f tmp/pids/server.pid ]] && rm -f tmp/pids/server.pid
 
     rails db:create db:migrate db:seed
-    rails s -b 0.0.0.0
-    [[ $? -eq 0 ]] && break
+    if [[ $? -eq 0 ]]; then
+        echo "Database setup successful."
+        break
+    else
+        echo "Database setup failed, retrying..."
+    fi
     sleep 2s
 done
+
+echo "Starting Rails server..."
+rails s -b 0.0.0.0
